# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello_django_app', '0003_proportion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proportion',
            name='recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hello_django_app.Recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proportion',
            name='value',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
